services:
  redis:
    image: "redis"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - internalnet
  restcontainer:
    image: esport
    container_name: rest
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - internalnet
    links:
      - redis
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

networks:
  internalnet:
    driver: bridge